name: Release Drafter

on:
 pull_request_target:
   types: [opened, synchronize, reopened]

jobs:
 update_release_draft:
   runs-on: ubuntu-latest
   steps:
     - uses: release-drafter/release-drafter@v5
       env:
         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
