name: Release Drafter CI

on:
  release:
    types: [published]
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  draft_release:
    name: Draft Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Current Branch (Fast)
        uses: actions/checkout@v4

      - id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: .github/release-drafter.yml
